apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      imagePullPolicy: Always
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 8081
          hostPort: 8081
      imagePullPolicy: Always
