apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    component: server
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      name: server
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: gcr.io/halogen-acumen-344711/server:1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: PORT
              value: '5432'
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-password
            - name: NODE_ENV
              value: "kubernetes"
      imagePullSecrets:
        - name: gcr-json-key
