apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    application: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      imagePullPolicy: Always