# docker-compose build
# docker-compose up -d
# docker-compose ps
# docker-compose logs -f app
# switch between docker normal build and dockerize
version: '3.7'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - db-net

  app:
    build: 
      context: .
      dockerfile: normal.DockerFile
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - db-net

networks:
  db-net:
    driver: bridge